export const types = {
  //FILTERS BY SEARCH
  F_DISABLE: "F_DISABLE",
  IMAGES: "IMAGES",
  VIDEOS: "VIDEOS",

  //SORTS BY SEARCH
  S_DISABLE: "S_DISABLE",
  M1_ASC: "M1_ASC",
  M1_DSC: "M1_DSC",
  M2_ASC: "M2_ASC",
  M2_DSC: "M2_DSC",
  M3_ASC: "M3_ASC",
  M3_DSC: "M3_DSC",

  //SHOW ITEM MODAL
  SET_ITEM: "SET_ITEM",
  UNSET_ITEM: "UNSET_ITEM",
};
