export const types = {
  //SORTS BY SEARCH
  DISABLE: "DISABLE",
  ID_ASC: "ID_ASC",
  ID_DSC: "ID_DSC",
  NAME_ASC: "NAME_ASC",
  NAME_DSC: "NAME_DSC",
  SECTOR_ASC: "SECTOR_ASC",
  SECTOR_DSC: "SECTOR_DSC",
  VIDEO: "VIDEO",
  IMAGE: "IMAGE",
  M1_ASC: "M1_ASC",
  M1_DSC: "M1_DSC",
  M2_ASC: "M2_ASC",
  M2_DSC: "M2_DSC",
  M3_ASC: "M3_ASC",
  M3_DSC: "M3_DSC",

  //SHOW ITEM MODAL
  SET_ITEM: "SET_ITEM",
  UNSET_ITEM: "UNSET_ITEM",

  //SEARCH
  SEARCH: "SEARCH",
  RESET_SEARCH: "RESET_SEARCH",
};
